package performancemap;

public enum MetricType {
    SCORE,
    DSR_PERCENTAGE,
    REJECT_PERCENTAGE,
    MPOS_PERCENTAGE,
    FALSE_DEL_SCANS_COUNT,
    FALSE_ATTEMPT_SCANS_COUNT,
    BHVRL_ISSUES_COUNT,
    SDS_NON_COMPLIANCE_UTL_COUNT,
    SDS_NON_COMPLIANCE_UTCR_COUNT,
    TOTAL_DEFECTS_COUNT,
    IHS_SAMMAAN_CONTEST_FOR_THE_MONTH,
    IHS_SAMMAAN_BENEFITS_COUNT,
    IHS_SAMMAAN_PERFORMANCE,
    IHS_SAMMAAN_DATA_UPDATED_TILL,
    IHS_SAMMAAN_RANK_IN_ZONE,
    IHS_SAMMAAN_TOTAL_AVAILABLE_POINTS,
    IHS_SAMMAAN_NEXT_SCHEDULE_TO_REDEEM_POINTS,

    /* POD Daily Metrics */
    STORE_ID,
    STATION_CODE,
    DATE_QUALIFIER,
    COD_DELIVERED,
    DPOD_PERF,
    DA_INITIATED_PERF,
    AUTOPAYLINK_PERF,
    CLR_PERF,
    OVERALL_POD_PERF,
    AGGREGATION_TYPE,

    /* POD Monthly Metrics */
    DPOD_TRANSACTIONS,
    DPOD_BASE_TARGET,
    DPOD_STRETCH_TARGET1,
    DPOD_STRETCH_TARGET2,
    OVERALL_POD_TARGET,
    TARGET_STATUS,
    FINAL_INCENTIVE,

    /* MAQ Daily */
    ONBOARDING_COMPLETED,

    /* MAQ Monthly */
    CURRENT_MONTH_ACQUISITION,
    ACQ_INCENTIVE,
    AMR_BASE,
    ACTIVE_MERCHANTS,
    AMR_PER,
    AMR_INCENTIVE,
    AMR_INCENTIVE_STATUS,

    /* KYC Daily/Monthly */
    FLAGGED_CUSTOMER,
    KYC_CUSTOMER,
    FLAGGED_KYC_CUSTOMER,
    FLAGGED_PER,
    KYC_INCEN
}